apiVersion: apps/v1
kind: Deployment
metadata:
  name: acs
  namespace: oktopus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: acs
    spec:
      containers:
        - name: acs
          image: oktopusp/acs:latest
            #image: miravallesg/acs:v1.1
          resources:
            # requests:
            #   memory: 64Mi
            #   cpu: 0.5
            # limits:
            #   memory: 256Mi
            #   cpu: 1
          imagePullPolicy: IfNotPresent
          env:
            - name: NATS_URL
              value: "nats://nats.oktopus:4222"
            - name: NATS_NAME
              value: "adapter"
            - name: NATS_VERIFY_CERTIFICATES
              value: "false"
            - name: CWMP_DEBUG
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: acs-svc
spec:
  selector:
    app: acs
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 9292
  type: ClusterIP

