apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oktopus-cert-letsencrypt-prod
  namespace: oktopus
spec:
  secretName: oktopus-cert-letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - oktopus.kube.cablevision-labs.com.ar

