apiVersion: v1
kind: ConfigMap
metadata:
  name: mitmproxy-script
  namespace: oktopus
data:
  inject_cookie.py: |
    from mitmproxy import http

    def request(flow: http.HTTPFlow) -> None:
        # Si la solicitud es POST a /acs, no inyectamos la cookie aún
        if flow.request.method == "POST" and "/acs" in flow.request.pretty_url:
            print(f"[inject_cookie] Primera solicitud /acs, no inyectando cookie aún.")
        else:
            cookies = flow.request.cookies
            if "oktopus" not in cookies:
                cookies["oktopus"] = "valor_default_o_dinámico"
                print(f"[inject_cookie] Cookie 'oktopus' inyectada: valor_default_o_dinámico")
            print(f"[inject_cookie] Cookies enviadas: {dict(cookies)}")

    def response(flow: http.HTTPFlow) -> None:
        # Verificamos si la respuesta es 401 y que sea una solicitud a /acs
        if flow.response.status_code == 401 and "/acs" in flow.request.pretty_url:
            print(f"[inject_cookie] Respuesta 401, esperando que la cookie 'oktopus' sea inyectada en la siguiente solicitud.")

